import { ObjectId } from "mongodb";
import { IDeletedCreatedData } from './dtd-declarer.dtd';
import { FetchableField } from "./fetchable-field";

export interface IBaseModel {
	/**
	 * If this model was generated by someone else
	 */
	_generatedFrom?: FetchableField<string>;
	/**
	 * MongoID of the document
	 */
	_id?: string | ObjectId;
	/**
	 * The model class of the object
	 */
	// _modelClass?: ModelClass;
	/**
	 * The info when and who created the document
	 */
	_created?: IDeletedCreatedData;
	/**
	 * The info when and who deleted the document
	 */
	_deleted?: IDeletedCreatedData;
	/**
	 * Some models could have progressive code
	 */
	_progCode?: number;
	/**
	 * The date that affects the system infos, instead of using ._created._timestamp use this 
	 */
	date?: number;
	/**
	 * Additional location id to control the physical location of an element
	 */
	physicalLocation?: string;
	/**
	 * The location id where the document was created
	 */
	documentLocation?: string;
	/**
	 * The location ids (MULTIPLE / ARRAY) where the document was created
	 */
	documentLocationsFilter: (string)[];

}