import { IBaseModel, FetchableField } from '@sixempress/main-fe-lib';
import CreditCard from '@material-ui/icons/CreditCard';
import AttachMoney from '@material-ui/icons/AttachMoney';
import HelpOutline from '@material-ui/icons/HelpOutline';
import Icon from '@material-ui/core/Icon';

export enum MovementDirection {
	input = 1,
	output,
	internalInput,
	internalOutput,
}

export enum MovementDirectionLabel {
	"Entrata" = 1,
	"Uscita",
	"Entrata Interna",
	"Uscita Interna",
}

export enum MovementMedium {
	unspecified = 1,
	cash,
	card,
}

export enum MovementMediumLabel {
	'Non specificato' = MovementMedium.unspecified,
	'Contanti' = MovementMedium.cash,
	'Carta' = MovementMedium.card,
};

export const MovementMediumIcons = {
	[MovementMedium.card]: <CreditCard/>,
	[MovementMedium.cash]: <AttachMoney/>,
	[MovementMedium.unspecified]: <HelpOutline/>,
}

export const MovementMediumMenuLabel = {
	[MovementMedium.card]: <Icon>{MovementMediumIcons[MovementMedium.card]}</Icon>,
	[MovementMedium.cash]: <Icon>{MovementMediumIcons[MovementMedium.cash]}</Icon>,
	[MovementMedium.unspecified]: <Icon>{MovementMediumIcons[MovementMedium.unspecified]}</Icon>,
};

export interface SplitReport {
	// [out, in]
	[modelClass: string]: [number, number],
	additional?: [number, number],
}

export interface Movement extends IBaseModel {
	date: number;
	description?: string;
	priceAmount: number;
	requireAttributeToSee?: true;
	
	direction: MovementDirection;
	medium: MovementMedium,
	
	/** The movement can be generated by another model, this is the ref to that model */
	_generatedFrom?: FetchableField<any>;
		
}

export interface MovementGraph {
	cashOut: number,
	cashIn: number,
	posIn: number,
	posOut: number,

	internalIn: number,
	internalOut: number,
}